version: 0.0
os: linux

files:
  - source: / # 인스턴스에 복사할 디렉터리 경로
    destination: /home/ec2-user/app/step1 # 인스턴스에서 파일이 복사되는 위치
    overwrite: yes # 복사할 위치에 파일이 있는 경우 대체

permissions:
  - object: / # 권한이 지정되는 파일 or 디렉터리

hooks:
  AfterInstall: # CodeDeploy의 AfterInstall 단계에서 실행
    - location: scripts/stop.sh # hooks에서 실행할 스크립트의 위치
      timeout: 60 # 스크립트 실행에 허용되는 최대 시간, 넘으면 배포 실패
  ApplicationStart: # CodeDeploy의 ApplicationStart 단계에서 실행
    - location: scripts/start.sh
      timeout: 60
