spring:
  datasource:
    url: jdbc:mysql://localhost:3306/house_rent?useSSL=false&allowPublicKeyRetrieval=true&useUnicode=true&serverTimezone=Asia/Seoul
    username: root
    password: dltnqls1234
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.orm.jdbc.bind: trace

seoul-api:
  baseUrl: "http://openapi.seoul.go.kr:8088"
  key: "5a75446d6b6c656539375244465959"
  dataType: "json"
  rent: "tbLnOpendataRentV"
  sale: "tbLnOpendataRtmsV"

juso-api:
  baseUrl: "https://business.juso.go.kr/addrlink/addrLinkApi.do"
  key: "U01TX0FVVEgyMDIzMDYwNzE4MDcyNzExMzgzMTI="
  resultType: "json"