# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  AWS_REGION: ap-northeast-2
  S3_BUCKET_NAME: house-rent-s3
  CODE_DEPLOY_APPLICATION_NAME: house-rent-deploy
  CODE_DEPLOY_DEPLOYMENT_GROUP_NAME: house-rent-deploy-agent
  
permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
    #- name: Run chmod to make gradlew executable
    #  run: chmod +x ./gradlew
    #- name: Build with Gradle
    #  run: ./gradlew build

    #- name: Configure AWS credentials		#aws credentials 생성
    #  uses: aws-actions/configure-aws-credentials@v1
    #  with:
    #    aws-access-key-id: ${{ secrets.AWS_ACCESS_ID }}	
    #    aws-secret-access-key: ${{ secrets.AWS_ACCESS_KEY }} 
    #    aws-region: ${{env.AWS_REGION}}
        
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v3
      with:
        aws-region: ${{env.AWS_REGION}}
        role-to-assume: arn:aws:iam::634903875227:role/house-rent-s3
        role-session-name: house-rent-s3

  # s3 업로드
    - name: upload build directory to s3
      run: aws s3 cp dist/ s3://your_bucket --recursive  #s3 bucket에 업로드
