# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  AWS_REGION: ap-northeast-2
  S3_BUCKET_NAME: house-rent-s3
  CODE_DEPLOY_APPLICATION_NAME: house-rent-deploy
  CODE_DEPLOY_DEPLOYMENT_GROUP_NAME: house-rent-deploy-agent
  
permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
    - name: Start MariaDB
      # You may pin to the exact commit or the version.
      # uses: getong/mariadb-action@acf7bc08e06a9c26e2a534d54284cb9a62697e7d
      uses: getong/mariadb-action@v1.1
      with:
        host port: 3306
        # The port of container
        container port: 3306
        # --character-set-server - The character set of MySQL server
        character set server: 'utf8mb4'
        collation server: 'utf8mb4_general_ci'
        # Version of MariaDB to use
        # MYSQL_ROOT_PASSWORD - root superuser password
        mysql root password: 'dltnqls^6^'
        # MYSQL_DATABASE - name for the default database that is created
        mysql database: 'house-rent'
        # MYSQL_USER - create the specified user with superuser power for created database
        mysql user: 'leesub0168'
        # MYSQL_PASSWORD - specified superuser password which user is power for created database
        mysql password: 'dltnqls^6^'
    - name: Run chmod to make gradlew executable
      run: chmod +x ./gradlew
    - name: Build with Gradle
      run: ./gradlew build

    - name: Configure AWS credentials		#aws credentials 생성
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_ID }}	
        aws-secret-access-key: ${{ secrets.AWS_ACCESS_KEY }} 
        aws-region: ap-northeast-2

  # s3 업로드
    - name: upload build directory to s3
      run: aws s3 cp dist/ s3://your_bucket --recursive  #s3 bucket에 업로드
